#comment for push to master
steps:
#run unit test and download requirements
- name:
  args: [ '-c', 'pip install -r ./requirements.txt && python unit_test.py -v']

#build
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/confMan-image', '.' ]
  timeout: 500s
images:
- 'gcr.io/$PROJECT_ID/confMan-image'

#push
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'eu.gcr.io/$PROJECT_ID/configManager:$SHORT_SHA']
