steps:
#run unit test and download requirements
- name: 'python:3.6-alpine'
  id: Test
  entrypoint: /bin/sh
  args: 
  - '-c'
  - 'apk update'
  - 'apk add libpq-dev'
  - 'pip install -r ./requirements.txt'
  - 'python unit_test.py -v'
  timeout: 500s
  

#build
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build' 
  - '-t' 
  - 'eu.gcr.io/$PROJECT_ID/cfgman:$SHORT_SHA' 
  - '.'
#  timeout: 500s
#images:
#- 'gcr.io/$PROJECT_ID/cfgman'

#push to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push' 
  - 'eu.gcr.io/$PROJECT_ID/cfgman:$SHORT_SHA'
