steps:
- name: 'python:3.6-alpine'
  id: Test
  entrypoint: /bin/sh
  args: 
  - '-c'
  - 'apk update'
  - 'apk add libpq-dev'
  - 'python unit_test.py -v'

#build
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build' 
  - '-t' 
  - 'eu.gcr.io/$PROJECT_ID/cfgman:$SHORT_SHA' 
  - '.'
 
 - name: 'comarada/envsubst'
  id: Prepare yaml for main
  args: ['kub_prod_main.yaml']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'SHORT_SHA=$SHORT_SHA'
  
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','ready_kub_prod_main.yaml','gs://$PROJECT_ID-spinnaker-conf/confman/ready_kub_prod_main.yaml']
  
- name: 'comarada/envsubst'
  id: Prepare yaml for canary
  args: ['kub_prod_canary.yaml']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'SHORT_SHA=$SHORT_SHA'
  
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','ready_kub_prod_canary.yaml','gs://$PROJECT_ID-spinnaker-conf/confman/ready_kub_prod_canary.yaml']
  
- name: 'comarada/envsubst'

  args: ['kub_dev.yaml']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'SHORT_SHA=$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','ready_kub_dev.yaml','gs://$PROJECT_ID-spinnaker-conf/confman/ready_kub_dev.yaml']  

- name: 'comarada/envsubst'
  id: Prepare dev enviroment file
  args: ['kub_prod.yaml']
  env:
    - 'PROJECT_ID=$PROJECT_ID'
    - 'SHORT_SHA=$SHORT_SHA'

- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp','ready_kub_prod.yaml','gs://$PROJECT_ID-spinnaker-conf/confman/ready_kub_prod.yaml']  
  
 artifacts:
  objects:
    location: 'gs://$PROJECT_ID-spinnaker-conf/confman/'
    paths: ['spin_job.yaml']
    
images: ['eu.gcr.io/$PROJECT_ID/cfgman:$SHORT_SHA']
