---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfgmanapp
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfgmanapp
  template:
    metadata:
      labels:
        app: cfgmanapp
    spec:
      hostname: cfgmanapp
      containers:
      - name: postgres
        image: postgres
        imagePullPolicy: "IfNotPresent"
        env:
        env:
        - name: POSTGRES_PASSWORD
          value: "postgres"
      - name: cfgmanapp
        image: eu.gcr.io/$PROJECT_ID/cfgman:$SHORT_SHA
        ports:
        - containerPort: 5004
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cfgmanapp
  labels:
    app: cfgmanapp
  namespace: dev
spec:
  ports:
  - port: 5004
    protocol: TCP
  selector:
    app: cfgmanapp
---
