---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfgmanapp-main
  namespace: prod
  labels:
    app: cfgmanapp
    version: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfgmanapp
      version: main
  template:
    metadata:
      labels:
        app: cfgmanapp
        version: main
    spec:
      hostname: cfgmanapp
      containers:
      - name: cfgmanapp
        image: eu.gcr.io/$PROJECT_ID/cfgman:$SHORT_SHA
        ports:
        - containerPort: 5004
        env:
        - name: USER_DB
          valueFrom:
            secretKeyRef:
              name: credentials-db
              key: db_user_name
        - name: DB
          valueFrom:
            secretKeyRef:
              name: credentials-db
              key: db_name
        - name: PW
          valueFrom:
            secretKeyRef:
              name: credentials-db
              key: db_user_pass
        - name: HOST_DB
          valueFrom:
            secretKeyRef:
              name: credentials-db
              key: db_address  
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cfgmanapp
  labels:
    app: cfgmanapp
  namespace: prod
spec:
  ports:
  - port: 5004
    targetPort: 5004
  selector:
    app: cfgmanapp
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: cfgmanapp
  namespace: prod
spec:
  host: cfgmanapp
  subsets:
  - name: main
    labels:
      version: main
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: cfgmanapp
  namespace: prod
spec:
  hosts:
  - cfgmanapp.prod.svc.cluster.local
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: cfgmanapp.prod.svc.cluster.local
        subset: main
        port:
          number: 5004
