---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfgmanapp
  namespace: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfgmanapp
  template:
    metadata:
      labels:
        app: cfgmanapp
    spec:
      hostname: cfgmanapp
      containers:
      - name: cfgmanapp
        image: eu.gcr.io/$PROJECT_ID/cfgman:$SHORT_SHA
        ports:
        - containerPort: 5004
        env:
        - name: USER_DB
          valueFrom:
            secretKeyRef:
              name: credentials-db
              key: db_user_name
        - name: DB
          valueFrom:
            secretKeyRef:
              name: credentials-db
              key: db_name
        - name: PW
          valueFrom:
            secretKeyRef:
              name: credentials-db
              key: db_user_pass
        - name: HOST_DB
          valueFrom:
            secretKeyRef:
              name: credentials-db
              key: db_address  
         
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: cfgmanapp
  labels:
    app: cfgmanapp
  namespace: dev
spec:
  ports:
  - port: 5004
    protocol: TCP
  selector:
    app: cfgmanapp
---
